### ISSUE TITLE
Add time range filter inputs to dataset details

### ISSUE THREAD

**Issue by michaelbrooks** [michaelbrooks/uw-message-coding#56]
The user can provide min/max times that will affect the messages displayed.

**Comment by nanchenchen** [comment]
Need a search input

**Comment by nanchenchen** [comment]
![image](https://cloud.githubusercontent.com/assets/3320040/5913121/6618f59e-a593-11e4-81f4-81b9283a7126.png)
Working prototype. Need to deal with different date-time format.

**Comment by nanchenchen** [comment]
Question: Where to submit the request for updating the on-going message set?

**Comment by michaelbrooks** [comment]
[This](https://docs.angularjs.org/api/ng/directive/ngChange) might be the solution to all our problems.

There's a method loadMessages that needs to get called to load messages for a page and filters. It's a bit awkward currently. It is private, so I think the easiest way to do it would be to add a public `refresh()` function or something that just calls it with no parameters. But I haven't really read how ngChange works carefully.
