### ISSUE TITLE
Fix API permissions

### ISSUE THREAD

**Issue by michaelbrooks** [michaelbrooks/uw-message-coding#70]
Get appropriate read/write permissions set up for the various API views.

**Comment by nanchenchen** [comment]
define cases that we can test

maybe try unit test

**Comment by nanchenchen** [comment]
From here: http://www.django-rest-framework.org/api-guide/permissions/#isauthenticated

**Comment by nanchenchen** [comment]
user: admin can POST, authenticated users can GET
all others: authenticated users can do any action?

**Comment by nanchenchen** [comment]
not the case: project owner and task workers should have different permissions on the project.

**Comment by michaelbrooks** [comment]
and users shouldn't be able to get information about projects they don't belong to

**Comment by nanchenchen** [comment]
okok

**Comment by nanchenchen** [comment]
Current setting: 
- only authenticated users can access the APIs (Mainly test in the API interface though. It seems to work fine on the main interface.)
- only super_user can modify users, otherwise read-only
- super_users can RW projects and tasks
- otherwise, only project owner can modify the project. Members have read-only permission.
- only task owner can modify the task, and task assigner can access the task. (not sure if we should allow project owner to modify the task.)

Not yet set permission on other APIs (probably knows how, but need to know what to set)

**Comment by nanchenchen** [comment]
docs:
- http://www.django-rest-framework.org/api-guide/permissions/
- http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/
- http://www.django-rest-framework.org/api-guide/authentication/

**Comment by michaelbrooks** [comment]
Great, thanks for figuring this out. The last thing here would be to create at least the groundwork for testing that we have this configured the way we thing we do. Since it's so confusing and there are so many cases, automatic tests are a good way to verify.

It looks like Django Rest Framework provides some features for this: http://www.django-rest-framework.org/api-guide/testing/

I don't think it's necessary to implement tests for all the cases you described above -- we can do that as it comes up -- but let's at least add one test of the API permissions. I would write these, for example, in `apps/project/tests/api.py`. I think Django will autodiscover them if you follow the proper conventions (extend one of the [TestCase](http://www.django-rest-framework.org/api-guide/testing/#test-cases) classes, begin your test method with `test_`). Don't forget to add an `__ini__.py` file in the tests folder to make it a python module.

**Comment by nanchenchen** [comment]
Note: users may need to modify themselves

**Comment by nanchenchen** [comment]
change permission to project members can modify/access project and tasks
