### ISSUE TITLE
Importing metadata

### ISSUE THREAD

**Issue by michaelbrooks** [michaelbrooks/uw-message-coding#93]
We must have the ability to import original ids along with the messages.

When we import data, do the following:
1. Read each CSV row in as a dictionary
2. Extract and remove the fields we understand (sender, text, time).
3. Convert the remaining dictionary into a json string and store it in a blob field on the messages.
4. Store the row headers in order from the csv reader in a field on the Dataset object.

**Comment by geosoco** [comment]
id is one of the more important fields needed to import here.
